import type { Metadata } from "next";
import { Exo } from "next/font/google";
import "./globals.css";
//import ParticlesBackground from "@/components/ParticlesBackground";
import dynamic from "next/dynamic";

const ParticlesBackground = dynamic(() => import("@/components/ParticlesBackground"), { ssr: false });
const exo = Exo({
  variable: "--font-exo",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Porfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="bg-black">
      <body
        className={` ${exo.variable} font-exo antialiased`}
      >
        {children}
        <ParticlesBackground />
      </body>
    </html>
  );
}
